apiVersion: cloudstackctl/v1
kind: Component
metadata:
  name: frontend
spec:
  virtualMachineSpec: frontend-vmspec
  replicas: 2
  overrides:
    template: my-template
    serviceOffering: small
  healthChecks:
    - type: ping
      interval: 10s
      timeout: 5s
