apiVersion: cloudstackctl/v1
kind: VirtualMachineSpec
metadata:
  name: backend-vmspec
spec:
  template: my-template
  serviceOffering: small
  networks:
    - example-network
  sshKeys:
    - my-key
  volumes:
    - name: data-disk
      type: data
      diskOffering: standard-hdd
      size: 50
